name: It's Monday! Time to Sync

on:
  schedule:
    - cron: "0 8 * * 1" # At 08:00 on Monday.

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  sync:
    name: Sync all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: Run script
        run: yarn sync-all
